export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const POST_LOADING = 'POST_LOADING';
export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const ADD_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';

// theme
export const UPDATE_DIRECTION = "UPDATE_DIRECTION";
export const UPDATE_LANGUAGE = "UPDATE_LANGUAGE";

// device
export const UPDATE_DEVICE = "UPDATE_DEVICE";

// Category
export const ADD_CATEGORY = "ADD_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const DELETE_CATEGORY = "DELETE_CATEGORYS";
export const CATEGORY_LOADING = "CATEGORY_LOADING";

// Sub Category
export const ADD_SUBCATEGORY = "ADD_SUBCATEGORY";
export const GET_SUBCATEGORIES = "GET_SUBCATEGORIES";
export const GET_SUBCATEGORY = "GET_SUBCATEGORY";
export const ADD_FIELD_TO_SUBCATEGORY = "ADD_FIELD_TO_SUBCATEGORY";
export const DELETE_FIELD_FROM_SUBCATEGORY = "DELETE_FIELD_FROM_SUBCATEGORY";
export const UPDATE_SUBCATEGORY = "UPDATE_SUBCATEGORY";
export const DELETE_SUBCATEGORY = "DELETE_SUBCATEGORY";
export const SUBCATEGORY_LOADING = "SUBCATEGORY_LOADING";

// Field
export const ADD_FIELD = "ADD_FIELD";
export const GET_FIELDS = "GET_FIELDS";
export const UPDATE_FIELD = "UPDATE_FIELD";
export const DELETE_FIELD = "DELETE_FIELD";

// FieldSpec
export const ADD_FIELDSPEC = "ADD_FIELDSPEC";
export const GET_FIELDSPECS = "GET_FIELDSPECS";
export const UPDATE_FIELDSPEC = "UPDATE_FIELDSPEC";
export const DELETE_FIELDSPEC = "DELETE_FIELDSPEC";

